<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-25 15:38

$extensionPath = t3lib_extMgm::extPath('ics_navitia_schedule');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_icsnavitiaschedule_bookmark' => $extensionClassesPath . 'class.tx_icsnavitiaschedule_bookmark.php',
	'tx_icsnavitiaschedule_departureboard' => $extensionClassesPath . 'class.tx_icsnavitiaschedule_departureBoard.php',
	'tx_icsnavitiaschedule_directionlist' => $extensionClassesPath . 'class.tx_icsnavitiaschedule_directionList.php',
	'tx_icsnavitiaschedule_linelist' => $extensionClassesPath . 'class.tx_icsnavitiaschedule_lineList.php',
	'tx_icsnavitiaschedule_nextdeparture' => $extensionClassesPath . 'class.tx_icsnavitiaschedule_nextDeparture.php',
	'tx_icsnavitiaschedule_pi1' => $extensionPath . 'pi1/class.tx_icsnavitiaschedule_pi1.php',
	'tx_icsnavitiaschedule_stoplist' => $extensionClassesPath . 'class.tx_icsnavitiaschedule_stopList.php',
);
?>