<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-08-25 12:30

$extensionPath = t3lib_extMgm::extPath('ics_navitia_schedule');
$extensionClassesPath = t3lib_extMgm::extPath('ics_navitia_schedule') . 'Classes/';
return array(
	'tx_icsnavitiaschedule_departureboard' => $extensionClassesPath . 'class.icsnavitiaschedule_departureBoard.php',
	'tx_icsnavitiaschedule_directionlist' => $extensionClassesPath . 'class.icsnavitiaschedule_directionList.php',
	'tx_icsnavitiaschedule_linelist' => $extensionClassesPath . 'class.icsnavitiaschedule_lineList.php',
	'tx_icsnavitiaschedule_stoplist' => $extensionClassesPath . 'class.icsnavitiaschedule_stopList.php',
	'tx_icsnavitiaschedule_pi1' => $extensionPath . 'pi1/class.tx_icsnavitiaschedule_pi1.php',
);
?>